import os
import glob
import numpy as np
import pandas as pd
import struct

File = 'R14_09950-v02.pos'
def read_epos(file):
    with open(file, 'rb') as in_file:
        file_size = os.path.getsize(file)
        n_row = int(file_size/44)
        data = np.zeros((n_row,11))
        for i in range(0,n_row):
            a = in_file.read(4*9)
            b = in_file.read(4*2)
            data[i,0:9] = np.asarray(struct.unpack('>9f',a))
            data[i,9:] = np.asarray(struct.unpack('2I',b))
    print("# of atoms =",n_row)
    return data

data = read_epos(File)
df = pd.DataFrame(data, columns=['x','y','z','m/n','TOF','V_DC','V_P','X_DET','Y_DET','Delta_P','N_M'])
store = pd.HDFStore('store_epos.h5')
store['data'] = df

### "fake_hit" mimick "hit" file generated by TAPSim-MD by including: tapsim-step md-step type id voltage onset_x onset_y onset_z hit_x hit_y hit_z time-of-fight

cnt = 0
with open('fake_hit', 'w+') as out_file:
    for i in data:
        cnt += 1
        out_file.write("%s %s %s %s %s %s %s %s %s %s %s %s\n" %(cnt, cnt, 1, cnt, 0.0, 0.0, 0.0, 0.0, i[7], i[8], 10, 0.0))
